from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class IamgeTestAssets: 


	# Image Rule Assets
	# description 
	I_LOGO = RuleImage(roi_front=(19,539,89,90), roi_back=(1,485,136,187), threshold=0.8, method="Template matching", file="./tasks/IamgeTest/res/res_logo.png")


