from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class FishingAssets: 


	# Image Rule Assets
	# 开始 
	I_DO1 = RuleImage(roi_front=(1162,515,38,40), roi_back=(1147,493,71,67), threshold=0.9, method="Template matching", file="./tasks/Fishing/Fishing_do1.png")
	# 等待上钩 
	I_DO2 = RuleImage(roi_front=(1163,507,43,35), roi_back=(1142,489,85,69), threshold=0.8, method="Template matching", file="./tasks/Fishing/Fishing_do2.png")
	# 中间等待 
	I_DO3 = RuleImage(roi_front=(1169,513,28,31), roi_back=(1147,492,72,60), threshold=0.8, method="Template matching", file="./tasks/Fishing/Fishing_do3.png")
	# 钓上来了，关闭按钮 
	I_CLONE = RuleImage(roi_front=(917,180,40,31), roi_back=(915,173,46,44), threshold=0.8, method="Template matching", file="./tasks/Fishing/Fishing_clone.png")


	# Ocr Rule Assets
	# 目标文字 
	O_TARGET = RuleOcr(roi=(486,96,45,34), area=(1,1,100,100), mode="Single", method="Default", keyword="Targe", name="target")


